version: "3.9"

services:
  cv-service-app:
    image: cv_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/CVService

  postgres:
    container_name: "postgresDB"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: CVService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - "CVService"

networks:
  CVService:
    driver: "bridge"
