spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        format_sql: 'true'
    hibernate:
      ddl-auto: none
  #    show-sql: 'true'
  liquibase:
    change-log: classpath:changelog/master.xml
    enabled: 'true'
    drop-first: 'false'
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/CVService
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER

file-storage:
  directory:
    root-path: CVService\fileStorage
    image: \images
    cv: \CVs

server:
  port: '8080'
